customer_first = Customer.create(first_name: 'Johny', last_name: 'Flow')
customer_second = Customer.create(first_name: 'Raj', last_name: 'Jamnis')
customer_third = Customer.create(first_name: 'Andrew', last_name: 'Chung')
customer_fourth = Customer.create(first_name: 'Mike', last_name: 'Smith')

Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_second)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_second)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_second)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_third)
Charge.create_successful(amount: 4900, currency: 'usd', customer: customer_fourth)

Charge.create_failed(amount: 4900, currency: 'usd', customer: customer_third)
Charge.create_failed(amount: 4900, currency: 'usd', customer: customer_third)
Charge.create_failed(amount: 4900, currency: 'usd', customer: customer_third)
Charge.create_failed(amount: 4900, currency: 'usd', customer: customer_fourth)
Charge.create_failed(amount: 4900, currency: 'usd', customer: customer_fourth)

Charge.create_disputed(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_disputed(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_disputed(amount: 4900, currency: 'usd', customer: customer_first)
Charge.create_disputed(amount: 4900, currency: 'usd', customer: customer_second)
Charge.create_disputed(amount: 4900, currency: 'usd', customer: customer_second)
